version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule: { interval: 'weekly' }
    open-pull-requests: { enabled: true }
  - package-ecosystem: 'pip'
    directory: '/inference'
    schedule: { interval: 'weekly' }
    open-pull-requests: { enabled: true }
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows'
    schedule: { interval: 'weekly' }
    open-pull-requests: { enabled: true }